prj/routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/







Auth::routes();
//
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])
    ->name('home');

Route::middleware(['auth'])->group(function() {


    Route::name('roles.')->prefix('roles')->group(function () {

        Route::get('/', [RoleController::class, 'index'])
            ->name('index')
        ->middleware('permission:view-roles');

        Route::get('/create', [RoleController::class, 'create'])
            ->name('create')
        ->middleware('permission:create-roles');

        Route::get('/show/{id}', [RoleController::class, 'show'])
            ->name('show')
        ->middleware('permission:show-roles');

        Route::get('/edit/{id}', [RoleController::class, 'edit'])
            ->name('edit')
        ->middleware('permission:edit-roles');

        Route::put('/update/{id}', [RoleController::class, 'update'])
            ->name('update')
        ->middleware('permission:update-roles');

        Route::delete('/destroy/{id}', [RoleController::class, 'destroy'])
            ->name('destroy')
        ->middleware('permission:destroy-roles');

        Route::post('/', [RoleController::class, 'store'])
            ->name('store')
        ->middleware('permission:store-roles');

    });

    Route::name('users.')->prefix('users')->group(function () {

        Route::get('/', [UserController::class, 'index'])
            ->name('index')
        ->middleware('permission:view-user');

        Route::get('/create', [UserController::class, 'create'])
            ->name('create')
        ->middleware('permission:create-user');

        Route::post('/store', [UserController::class, 'store'])
            ->name('store')
        ->middleware('permission:store-user');

        Route::get('/show/{id}', [UserController::class, 'show'])
            ->name('show')
        ->middleware('permission:show-user');

        Route::get('/edit/{id}', [UserController::class, 'edit'])
            ->name('edit')
        ->middleware('permission:edit-user');

        Route::put('/update/{id}', [UserController::class, 'update'])
            ->name('update')
        ->middleware('permission:update-user');

        Route::delete('/destroy/{id}', [UserController::class, 'destroy'])
            ->name('destroy')
        ->middleware('permission:destroy-user');

    });
    Route::name('categories.')->prefix('categories')->group(function () {

        Route::get('/', [CategoryController::class,'index'])
            ->name('index')
            ->middleware('permission:index-category');

        Route::get('/create', [CategoryController::class,'create'])
            ->name('create')
            ->middleware('permission:create-category');

        Route::post('/store', [CategoryController::class,'store'])
            ->name('store')
            ->middleware('permission:store-category');

        Route::get('/show/{id}', [CategoryController::class,'show'])
            ->name('show')
            ->middleware('permission:show-category');

        Route::get('/edit/{id}', [CategoryController::class,'edit'])
            ->name('edit')
            ->middleware('permission:edit-category');

        Route::put('/update/{id}', [CategoryController::class,'update'])
            ->name('update')
            ->middleware('permission:update-category');

        Route::delete('/destroy/{id}', [CategoryController::class,'destroy'])
            ->name('destroy')
            ->middleware('permission:destroy-category');

    });


    Route::name('products.')->prefix('products')->group(function () {

        Route::get('/', [ProductController::class, 'index'])
            ->name('index')
            ->middleware('permission:view-product');
        Route::get('/table', [ProductController::class, 'table'])
            ->name('table')
            ->middleware('permission:view-product');

        Route::get('/search', [ProductController::class, 'search'])
            ->name('search')
            ->middleware('permission:view-product');

        Route::get('/edit/{id}', [ProductController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:edit-product');

        Route::post('/store', [ProductController::class, 'store'])
            ->name('store')
            ->middleware('permission:store-product');

        Route::get('/show/{id}', [ProductController::class, 'show'])
            ->name('show')
            ->middleware('permission:show-product');

        Route::get('/create', [ProductController::class, 'create'])
            ->name('create')
            ->middleware('permission:create-product');

        Route::put('/update/{id}', [ProductController::class, 'update'])
            ->name('update')
            ->middleware('permission:update-product');

        Route::delete('/delete.{id}', [ProductController::class, 'delete'])
            ->name('delete')
            ->middleware('permission:delete-product');
    });
});

prj/resources/views/admin/Layouts/sidebar.blade.php
<aside
    class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark"
    id="sidenav-main">
    <div class="sidenav-header">
        <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
           aria-hidden="true" id="iconSidenav"></i>
{{--       <img src="https://demos.creative-tim.com/material-dashboard/assets/img/logo-ct.png">--}}
        <a class="navbar-brand m-0" href=" https://demos.creative-tim.com/material-dashboard/pages/dashboard " target="_blank">
            <img src="https://demos.creative-tim.com/material-dashboard/assets/img/logo-ct.png" class="navbar-brand-img h-100" alt="main_logo">
            <span class="ms-1 font-weight-bold text-white">Admin</span>
        </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto  max-height-vh-100" id="sidenav-collapse-main">
        <ul class="navbar-nav "  >
{{--            <li class="nav-item">--}}
{{--                <a class="nav-link text-white  {{ request()->route('roles.*') ? 'bg-gradient-primary active' : '' }}"--}}
{{--                   href="{{ route('roles.index') }}">--}}
{{--                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">--}}
{{--                        <i class="material-icons opacity-10">dashboard</i>--}}
{{--                    </div>--}}
{{--                    <span class="nav-link-text ms-1">Roles</span>--}}
{{--                </a>--}}

{{--            </li>--}}
            <li class="nav-item">
                <a class="nav-link text-white {{ request()->routeIs('roles.*') ? 'btn btn-success active' : '' }}" href="{{route('roles.index')}}">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">table_view</i>
                    </div>
                    <span class="nav-link-text ms-1">Role</span>
                </a>
            </li>
{{--            <li class="nav-item">--}}
{{--                <a class="nav-link text-white {{ request()->route('users.*') ? 'bg-gradient-primary active' : '' }} "--}}
{{--                   href="{{ route('users.index') }}">--}}
{{--                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">--}}
{{--                        <i class="material-icons opacity-10">table_view</i>--}}
{{--                    </div>--}}
{{--                    <span class="nav-lrink-text ms-1">User</span>--}}
{{--                </a>--}}
{{--            </li>--}}
            <li class="nav-item">
                <a class="nav-link text-white {{ request()->routeIs('users.*') ? 'btn btn-secondary active' : '' }}" href="{{route('users.index')}}">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">table_view</i>
                    </div>
                    <span class="nav-link-text ms-1">Users</span>
                </a>
            </li>
{{--            <li class="nav-item">--}}
{{--                <a class="nav-link text-white {{ request()->route('categories.*') ? "bg-gradient-primary " : '' }} "--}}
{{--                   href="{{ route('categories.index') }}">--}}
{{--                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">--}}
{{--                        <i class="material-icons opacity-10">receipt_long</i>--}}
{{--                    </div>--}}
{{--                    <span class="nav-link-text ms-1">Category</span>--}}
{{--                </a>--}}
{{--            </li>--}}
            <li class="nav-item">
                <a class="nav-link text-white {{ request()->routeIs('categories.*') ? 'btn btn-success active' : '' }}" href="{{route('categories.index')}}">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">table_view</i>
                    </div>
                    <span class="nav-link-text ms-1">Category</span>
                </a>
            </li>
{{--            <li class="nav-item">--}}
{{--                <a class="nav-link text-white {{ request()->route('products.*') ? "btn btn-danger " : '' }} "--}}
{{--                   href="{{ route('products.index') }}">--}}
{{--                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">--}}
{{--                        <i class="material-icons opacity-10">view_in_ar</i>--}}
{{--                    </div>--}}
{{--                    <span class="nav-link-text ms-1">Product</span>--}}
{{--                </a>--}}
{{--            </li>--}}
            <li class="nav-item">
                <a class="nav-link text-white {{ request()->routeIs('products.*') ? 'btn btn-success active' : '' }}" href="{{route('products.index')}}">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">table_view</i>
                    </div>
                    <span class="nav-link-text ms-1">Product</span>
                </a>
            </li>

        </ul>
    </div>
    <div class="sidenav-footer position-absolute w-100 bottom-0 ">
        <div class="mx-3">
{{--            <a class="btn bg-gradient-primary mt-4 w-100"--}}
{{--               href="https://www.creative-tim.com/product/material-dashboard-pro?ref=sidebarfree" type="button">Upgrade--}}
{{--                to pro</a>--}}
        </div>
    </div>
</aside>