prj/routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/







Auth::routes();
//
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])
    ->name('home');

Route::middleware(['auth'])->group(function() {


    Route::name('roles.')->prefix('roles')->group(function () {

        Route::get('/', [RoleController::class, 'index'])
            ->name('index')
        ->middleware('permission:view-roles');

        Route::get('/create', [RoleController::class, 'create'])
            ->name('create')
        ->middleware('permission:create-roles');

        Route::get('/show/{id}', [RoleController::class, 'show'])
            ->name('show')
        ->middleware('permission:show-roles');

        Route::get('/edit/{id}', [RoleController::class, 'edit'])
            ->name('edit')
        ->middleware('permission:edit-roles');

        Route::put('/update/{id}', [RoleController::class, 'update'])
            ->name('update')
        ->middleware('permission:update-roles');

        Route::delete('/destroy/{id}', [RoleController::class, 'destroy'])
            ->name('destroy')
        ->middleware('permission:destroy-roles');

        Route::post('/', [RoleController::class, 'store'])
            ->name('store')
        ->middleware('permission:store-roles');

    });

    Route::name('users.')->prefix('users')->group(function () {

        Route::get('/', [UserController::class, 'index'])
            ->name('index')
        ->middleware('permission:view-user');

        Route::get('/create', [UserController::class, 'create'])
            ->name('create')
        ->middleware('permission:create-user');

        Route::post('/store', [UserController::class, 'store'])
            ->name('store')
        ->middleware('permission:store-user');

        Route::get('/show/{id}', [UserController::class, 'show'])
            ->name('show')
        ->middleware('permission:show-user');

        Route::get('/edit/{id}', [UserController::class, 'edit'])
            ->name('edit')
        ->middleware('permission:edit-user');

        Route::put('/update/{id}', [UserController::class, 'update'])
            ->name('update')
        ->middleware('permission:update-user');

        Route::delete('/destroy/{id}', [UserController::class, 'destroy'])
            ->name('destroy')
        ->middleware('permission:destroy-user');

    });
    Route::name('categories.')->prefix('categories')->group(function () {

        Route::get('/', [CategoryController::class,'index'])
            ->name('index')
            ->middleware('permission:index-category');

        Route::get('/create', [CategoryController::class,'create'])
            ->name('create')
            ->middleware('permission:create-category');

        Route::post('/store', [CategoryController::class,'store'])
            ->name('store')
            ->middleware('permission:store-category');

        Route::get('/show/{id}', [CategoryController::class,'show'])
            ->name('show')
            ->middleware('permission:show-category');

        Route::get('/edit/{id}', [CategoryController::class,'edit'])
            ->name('edit')
            ->middleware('permission:edit-category');

        Route::put('/update/{id}', [CategoryController::class,'update'])
            ->name('update')
            ->middleware('permission:update-category');

        Route::delete('/destroy/{id}', [CategoryController::class,'destroy'])
            ->name('destroy')
            ->middleware('permission:destroy-category');

    });


    Route::name('products.')->prefix('products')->group(function () {

        Route::get('/', [ProductController::class, 'index'])
            ->name('index')
            ->middleware('permission:view-product');
        Route::get('/table', [ProductController::class, 'table'])
            ->name('table')
            ->middleware('permission:view-product');

        Route::get('/search', [ProductController::class, 'search'])
            ->name('search')
            ->middleware('permission:view-product');

        Route::get('/edit/{id}', [ProductController::class, 'edit'])
            ->name('edit')
            ->middleware('permission:edit-product');

        Route::post('/store', [ProductController::class, 'store'])
            ->name('store')
            ->middleware('permission:store-product');

        Route::get('/show/{id}', [ProductController::class, 'show'])
            ->name('show')
            ->middleware('permission:show-product');

        Route::get('/create', [ProductController::class, 'create'])
            ->name('create')
            ->middleware('permission:create-product');

        Route::put('/update/{id}', [ProductController::class, 'update'])
            ->name('update')
            ->middleware('permission:update-product');

        Route::delete('/delete.{id}', [ProductController::class, 'delete'])
            ->name('delete')
            ->middleware('permission:delete-product');
    });
});

prj/app/Models/Product.php
<?php

namespace App\Models;

use App\Traits\HandleImage;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    use HandleImage;

    protected $table = "products";
    protected $fillable = [

            'image',
            'price',
            'describe'
        ];

    public function categories()
    {
        return $this->belongsToMany(
            Category::class,
            'product_category',
            'product_id',
            'category_id'
        );
    }

    public function addCategories($categoryIds)
    {
        return $this->categories()->attach($categoryIds);
    }

    public function syncCategories($categoryIds)
    {
        return $this->categories()->sync($categoryIds);
    }

    public function detachCategory()
    {
        return $this->categories()->detach();
    }

    public function getCategoryName()
    {
        return $this->categories->pluck('name');
    }

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%') : null;
    }

    public function scopeWithCategoryId($query, $id)
    {
        return $id ? $query->WhereHas(
            'categories',
            function ($query) use ($id) {
                $query->where('id', $id);
            }
        ) : null;
    }

    public function scopeWithCategory($query, $categoryId)
    {
        return $categoryId ? $query->whereHas(
            'categories',
            function ($query) use ($categoryId) {
                $query->where('id', $categoryId);
            }
        ) : null;
    }

    public function scopeWithMinPrice($query, $minPrice)
    {
        return $minPrice ? $query->where('price', '>', $minPrice) : null;
    }

    public function scopeWithMaxPrice($query, $maxPrice)
    {
        return $maxPrice ? $query->where('price', '<', $maxPrice) : null;
    }

    public function getImageAttribute($image)
    {
        return $image ? asset(config('image.path'). '/' .$image) : asset(config('image.imageDefault'));
    }
}

prj/app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Product\ProductCreateRequest;
use App\Http\Requests\Product\ProductUpdateRequest;
use App\Http\Resources\ProductResource;
use App\Models\Product;
use App\Services\CategoryService;
use App\Services\ProductService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ProductController extends Controller
{
    protected $categoryservice;


    public function __construct(
        CategoryService $categoryservice,
        ProductService $productService
    ) {
        $this->categoryservice = $categoryservice;
        $this->productService = $productService;
    }

    public function index()
    {
        $products = $this->productService->all();
        $categories = $this->categoryservice->all();
        return view('admin.products.index', compact('products', 'categories'));
    }

    public function create()
    {
        $categories = $this->categoryservice->all();
        $products = $this->productService->all();
        return view('products.create', compact('products', 'categories'));
    }

    public function show($id)
    {
        $product = $this->productService->findOrFail($id);
        return $this->responseSuccsess(new ProductResource($product), 'success', Response::HTTP_OK);
    }

    public function store(ProductCreateRequest $request)
    {

        $product = $this->productService->create($request);
        $productResource = new ProductResource($product);
        return $this->responseSuccsess($productResource, 'Save success', Response::HTTP_OK);
    }

    public function findOrFail($id)
    {
        $product = $this->productService->findOrFail($id);

        return view('products.show', compact('product'));
    }

    public function edit($id)
    {
        $product = $this->productService->findOrFail($id);
        return $this->responseSuccsess(new ProductResource($product), 'successfully', Response::HTTP_OK);
    }

    public function table(Request $request)
    {
        $products = $this->productService->search($request);
        return view('admin.products.list', compact('products'));
    }

    public function update(ProductUpdateRequest $request, $id)
    {
        $product = $this->productService->update($request, $id);
        $productResource = new ProductResource($product);
        return $this->responseSuccsess($product, 'Update success', Response::HTTP_OK);
    }

    public function delete($id)
    {
        $this->productService->delete($id);
        return $this->responseSuccsess('', 'Delete success', Response::HTTP_OK);
    }
}

prj/resources/views/admin/products/create.blade.php
<div class="container modal fade" id="modal-add">
    <div class="modal-dialog">
        <div class="modal-content">
            <div style="margin: 20px 20px 20px 20px;">
                <h1>Add New Product</h1>
                <div class="mb-3">
                    <a style="float:right" class="btn btn-secondary" id="close-add">Back</a>
                    </br>
                </div>
                <form id="form-add" method="post" enctype="multipart/form-data">
                    <div class="mb-3">
                        <label class="form-label"><strong>Name </strong></label>
                        <input type="text" name="name" class="form-control" id="name-add">
                        <div class="text-danger create-error"><span id="name-error"></span></div>
                    </div>

                    <div class="mb-3">
                        <label class="form-label"><strong>Price</strong> </label>
                        <input type="number" name="price" class="form-control" id="price-add">
                        <div class="text-danger create-error"><span id="price-error"></span></div>
                    </div>

                    <div class="mb-3">
                        <label class="form-label"><strong>Describe</strong></label>
                        <input type="text" name="describe" class="form-control" id="describe-add">
                        <div class="text-danger create-error"><span id="description-error"></span></div>
                    </div>

                    <div class="mb-3">
                        <label class="form-label"><strong>Image</strong> </label>
                        <img id="img-add-output"/>
                        <input type="file" name="image" accept="image/*" class="form-control" id="image-add">
                        <div class="text-danger create-error"><span id="image-error"></span></div>
                    </div>

                    <div class="mb-3">
                        <label class="form-label"><strong>Category</strong></label>
                        <select class="form-select" name="category_ids[]" id="category-add" multiple>
                            @foreach ($categories as $category)
                                <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <button class="btn btn-primary btn-store"  id="btn-create"
                            data-url="{{route('products.store')}}">Submit
                    </button>
                </form>

            </div>


        </div>
    </div>
</div>

prj/resources/views/admin/products/edit.blade.php
<div class="container modal fade" id="modal-edit">
    <div class="modal-dialog">
        <div class="modal-content">
            <div style="margin: 20px 20px 20px 20px;">
                <h1 id="title-edit">Edit Product </h1>
                <div class="mb-3">
                    <a style="float:right" class="btn btn-secondary" id="close-edit">Back</a>
                    </br>
                </div>
                <div id="product-id"></div>
                <form id="form-edit" enctype="multipart/form-data" data-action="" method="put">
                    <div class="mb-3">
                        <label class="form-label">Name </label>
                        <input type="text" name="name" class="form-control" id="name-edit">
                        <div class="text-danger edit-error"><span id="name-error"></span></div>
                        @error('name')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Price </label>
                        <input type="number" name="price" class="form-control" id="price-edit">
                        <div class="text-danger edit-error"><span id="price-error"></span></div>
                        @error('price')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Describe</label>
                        <input type="text" name="description" class="form-control" id="description-edit">
                        <div class="text-danger edit-error"><span id="description-error"></span></div>
                        @error('description')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Image </label></br>
                        <img class="rounded bg-light image-data img-thumbnail" accept="image/*"
                             style="file" id="product-image-edit" src=""/>
                        <input accept="image/*" type="file" name="image" class="form-control" placeholder="Post Image"
                               id="image-edit" hidden>
                        <div class="text-danger edit-error"><span id="image-error"></span></div>
                        @error('image')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Category</label>
                        <select class="form-select" name="category_ids[]" id="category-edit" multiple>
                            @foreach ($categories as $category)
                                <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <button type="submit" id="btn-update"   class="btn btn-primary btn-update"
                            data-action="">Submit
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

prj/resources/views/admin/products/index.blade.php
@extends('admin.Layouts.app')

@section('content')
    <div class="container">

        @if (session('message'))
            <div class="alert alert-primary" role="alert">
                {{ session('message') }}
            </div>
        @endif
        <div>
            <h1>LIST PRODUCT</h1>
        </div>
        <div>

            <a class="btn btn-primary btn-add" data-url="{{route('products.create')}}">Add</a>

        </div>
        <br>
        <div class="form-search">
            <form method="get" id="search-product">
                <div class="mb-3" style="display:flex">
                    <label class="form-label">Name&emsp;</label>
                    <input value="{{request()->name ?? ''}}" placeholder="abcd" type="text" name="name"
                           class="form-control"
                           style="padding-left: 10px; background-color: #fff; border: 1px solid #e7ebf0;">
                </div>
                <div class="mb-3" style="display:flex">
                    <label class="form-label">Price&emsp;</label>
                    <input value="{{request()->min_price ?? ''}}" placeholder="Min Price" type="number" name="min_price"
                           step="10000" min="0" class="form-control"
                           style="padding-left: 10px; background-color: #fff; border: 1px solid #e7ebf0;">
                    <input value="{{request()->max_price ?? ''}}" placeholder="Max Price" type="number" name="max_price"
                           step="10000" min="0" class="form-control"
                           style="padding-left: 10px; background-color: #fff; border: 1px solid #e7ebf0;">
                </div>
                <div class="mb-3" style="display:flex">
                    <label class="form-label">Category&emsp;</label>
                    <select class="form-select" name="category" type="text"
                            style="padding-left: 10px; background-color: #fff; border: 1px solid #e7ebf0;">
                        <option value="" >Select</option>
                        @foreach($categories as $category)
                            <option
                                value="{{$category->id}}" {{ request()->category_id == $category->id ? 'selected' : '' }}>{{$category->name}}</option>
                        @endforeach
                    </select>
                </div>
                <button class="btn btn-success search-product" type="submit">Search</button>
            </form>
        </div>
        <div>
            <div class="row" id="show-product" data-action-table="{{route('products.table')}}"></div>
        </div>


    </div>
    @include('admin.products.show')
    @include('admin.products.create')
    @include('admin.products.edit')
@endsection
<script src="{{asset('js/jquery.min.js')}}" defer></script>
<script src="{{asset('js/base.js')}}" defer></script>
<script src="{{asset('js/product.js')}}" defer></script>
<script src="{{asset('js/toastr.js')}}"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

prj/resources/views/admin/products/list.blade.php
<div id="show-product">
    <div class="table-responsive pt-3">
        <div style="display: none;">{{$stt = 0}}</div>
        <table class="table table hover">
            <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Price</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <div id="show_product"></div>
            @foreach ($products as $product)
                <tr>
                    <th>{{ $stt=$stt+1 }}</th>
                    <th>{{$product->name}}</th>
                    <th>{{$product->price}}</th>
                    <td>
                        <a class="btn btn-info btn-show"
                           data-url-show="{{route('products.show',$product->id)}}">Show</a>

                        <a class="btn btn-warning btn-edit" data-url="{{route('products.edit',$product->id)}}">Edit</a>

                        <button type="button" class="btn btn-danger btn-delete" value="{{$product->id}}"
                                data-url="{{route('products.delete',$product->id)}}">Delete
                        </button>
                    </td>
                </tr>
            @endforeach

            </tbody>
        </table>
    </div>
</div>
{{ $products->links('vendor.pagination.bootstrap-4') }}

prj/resources/views/admin/products/show.blade.php
<div class="container modal fade" id="modal-show">
    <div class="modal-dialog">
        <div class="modal-content">
            <div style="margin: 20px 20px 20px 20px;">
                <div>
                    <h1 id="product-title"> Show Product </h1>
                </div>
                <div class="mb-3">

                </div>
                <div class="panel-group">
                    <div class="mb-3">
                        <div class="panel-heading"><strong>Name</strong></div>
                        <div class="panel-body" id="product-name"></div>
                    </div>
                    <div class="mb-3">
                        <div class="panel-heading"><strong>Price</strong></div>
                        <div class="panel-body" id="product-price"></div>
                    </div>
                    <div class="mb-3">
                        <div class="panel-heading"><strong>Describe</strong></div>

                        <textarea size="5" class="form-select" name="describe" id="product-description" multiple>
                        </textarea>

                    </div>
{{--                    <div class="mb-3">--}}
{{--                        <label class="form-label">Describe</label>--}}
{{--                        <ul class="form-select"   multiple>--}}
{{--                            <li size="5" class="form-select" name="describe" id="product-description" multiple>--}}
{{--                                <option class="form-select" ></option>--}}
{{--                            </li>--}}
{{--                        </ul>--}}
{{--                    </div>--}}
                    <div class="mb-3">
                        <div class="panel-heading"><strong>Category</strong></div>
                        <div class="panel-body" id="product-category"></div>
                    </div>
                    <div class="mb-3">
                        <div class="panel-heading"><strong>Image</strong></div>
                        <div class="panel-body" id="product-imaged"></div>
                        <img class="rounded bg-light image-data img-thumbnail"
                             style="max-width: 70%; height: auto;" id="product-image" src=""/>
                    </div>
                </div>
                <a class="btn btn-secondary" id="close-show" data-dismiss="modal">Close</a>
            </div>
        </div>
    </div>
</div>